apiVersion: apps/v1
kind: Deployment
metadata:
  name: pep-pdp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: pep-pdp-deployment
          image: "harbor.tango.rid-intrasoft.eu/pdp-pep/pdp-pep:latest_dev"
          ports:
            - containerPort: 8088
          env:
             - name: PDP_PORT
               value: "8088"
             - name: PDP_CONFIG
               value: "test"
             - name: PDP_KS
               value: "/app/crypto/serverErat.ks"
             - name: PDP_PW
               value: "hola123"
             - name: PDP_ALIAS
               value: "MiAliasPriv"
             - name: DLT_IP
               value: "erat-server"
             - name: DLT_PORT
               value: "8086"
             - name: IDAGENT_KS
               value: "/app/crypto/ec-cakey.jks"
             - name: IDAGENT_PW
               value: "hola123"
             - name: IDAGENT_ALIAS
               value: "myserver"
             - name: IDAGENT_CERT
               value: "/app/crypto/ec-cacert.pem"
             - name: IDAGENT_IP
               value: "127.21.0.4"
             - name: IDAGENT_PORT
               value: "8082"
             - name: RESOURCES
               value: "/app/resources"
             - name: CT_EXPIRATION
               value: "2600000"
          volumeMounts:
            - name: build-libs
              mountPath: /app/build/libs
            - name: crypto
              mountPath: /app/crypto
            - name: ec-cakey-jks
              mountPath: /app/crypto/ec-cakey.jks
              subPath: ec-cakey.jks
            - name: ec-cacert-pem
              mountPath: /app/crypto/ec-cacert.pem
              subPath: ec-cacert.pem
            - name: resources
              mountPath: /app/resources
            - name: temperatura
              mountPath: /app/temperatura
      volumes:
        - name: build-libs
          hostPath:
            path: /home/natalia/git/local_repo/demo/libs
        - name: crypto
          hostPath:
            path: /home/natalia/git/local_repo/demo/crypto
        - name: ec-cakey-jks
          hostPath:
            path: /home/natalia/git/local_repo/demo/crypto
        - name: ec-cacert-pem
          hostPath:
            path: /home/natalia/git/local_repo/demo/crypto
        - name: resources
          hostPath:
            path: /home/natalia/git/local_repo/demo/resources
        - name: temperatura
          hostPath:
            path: /home/natalia/git/local_repo/demo/resources/temperatura

