apiVersion: v1
kind: Service
metadata:
  name:  pep-pdp-deployment
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80 # El puerto externo
      targetPort: 8088 # El puerto del contenedor

